# Generated by Django 3.2.5 on 2023-08-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230805_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='html_file',
            field=models.CharField(max_length=100),
        ),
    ]
