# Generated by Django 5.1.7 on 2025-03-23 17:40

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(max_length=255, verbose_name="Scientific Name"),
                ),
                (
                    "common_name",
                    models.CharField(max_length=255, verbose_name="Common Name"),
                ),
                (
                    "family",
                    models.CharField(blank=True, max_length=255, verbose_name="Family"),
                ),
                (
                    "native",
                    models.BooleanField(default=False, verbose_name="Native Species"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "average_height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Average Height (m)"
                    ),
                ),
                (
                    "average_canopy_diameter",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Average Canopy Diameter (m)",
                    ),
                ),
                (
                    "growth_rate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow", "Slow"),
                            ("medium", "Medium"),
                            ("fast", "Fast"),
                        ],
                        max_length=10,
                        verbose_name="Growth Rate",
                    ),
                ),
                (
                    "carbon_sequestration",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Carbon Sequestration (kg/year)",
                    ),
                ),
                (
                    "oxygen_production",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="Oxygen Production (kg/year)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Species",
                "verbose_name_plural": "Species",
                "ordering": ["scientific_name"],
            },
        ),
        migrations.CreateModel(
            name="Tree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="Location"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Neighborhood"
                    ),
                ),
                (
                    "height",
                    models.FloatField(blank=True, null=True, verbose_name="Height (m)"),
                ),
                (
                    "trunk_diameter",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Trunk Diameter (cm)"
                    ),
                ),
                (
                    "canopy_diameter",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Canopy Diameter (m)"
                    ),
                ),
                (
                    "estimated_age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Estimated Age (years)"
                    ),
                ),
                (
                    "planting_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Planting Date"
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                            ("dead", "Dead"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="Health Status",
                    ),
                ),
                (
                    "health_notes",
                    models.TextField(blank=True, verbose_name="Health Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Inspection Date"
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trees",
                        to="trees.species",
                        verbose_name="Species",
                    ),
                ),
            ],
            options={
                "ordering": ["species", "location"],
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("pruning", "Pruning"),
                            ("fertilization", "Fertilization"),
                            ("pest_control", "Pest Control"),
                            ("disease_treatment", "Disease Treatment"),
                            ("watering", "Watering"),
                            ("staking", "Staking"),
                            ("mulching", "Mulching"),
                            ("removal", "Removal"),
                            ("planting", "Planting"),
                            ("inspection", "Inspection"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Maintenance Type",
                    ),
                ),
                ("date_performed", models.DateField(verbose_name="Date Performed")),
                (
                    "performed_by",
                    models.CharField(max_length=255, verbose_name="Performed By"),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "before_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                            ("dead", "Dead"),
                        ],
                        max_length=20,
                        verbose_name="Health Before",
                    ),
                ),
                (
                    "after_health",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                            ("dead", "Dead"),
                        ],
                        max_length=20,
                        verbose_name="Health After",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="trees.tree",
                        verbose_name="Tree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance Record",
                "verbose_name_plural": "Maintenance Records",
                "ordering": ["-date_performed"],
            },
        ),
    ]
