# Generated by Django 5.1.7 on 2025-04-09 19:08

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiodiversityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "common_names",
                    models.TextField(blank=True, verbose_name="common names"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="location"
                    ),
                ),
                (
                    "elevation_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="elevation (m)"
                    ),
                ),
                (
                    "registered_by",
                    models.CharField(
                        blank=True,
                        default="Cortolima",
                        max_length=255,
                        verbose_name="registered by",
                    ),
                ),
                (
                    "registered_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="registered date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "biodiversity record",
                "verbose_name_plural": "biodiversity records",
                "ordering": ["species", "location"],
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="family name"
                    ),
                ),
            ],
            options={
                "verbose_name": "family",
                "verbose_name_plural": "families",
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="genus name"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genera",
                        to="trees.family",
                        verbose_name="family",
                    ),
                ),
            ],
            options={
                "verbose_name": "genus",
                "verbose_name_plural": "genera",
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="measurement name"),
                ),
                ("value", models.FloatField(verbose_name="measurement value")),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="measurement method"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="measurement date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "biodiversity_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="trees.biodiversityrecord",
                        verbose_name="biodiversity record",
                    ),
                ),
            ],
            options={
                "verbose_name": "measurement",
                "verbose_name_plural": "measurements",
                "ordering": ["biodiversity_record", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Colombia", max_length=255, verbose_name="country"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        default="Tolima", max_length=255, verbose_name="department"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        default="Ibagué", max_length=255, verbose_name="municipality"
                    ),
                ),
                (
                    "populated_center",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="populated center"
                    ),
                ),
                (
                    "zone",
                    models.CharField(blank=True, max_length=255, verbose_name="zone"),
                ),
                (
                    "subzone",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="subzone"
                    ),
                ),
                (
                    "site",
                    models.CharField(blank=True, max_length=255, verbose_name="site"),
                ),
                (
                    "created_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="created by"
                    ),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="updated by"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "place",
                "verbose_name_plural": "places",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "department", "municipality", "site"),
                        name="unique_place",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="biodiversityrecord",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="biodiversity_records",
                to="trees.place",
                verbose_name="place",
            ),
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="species name")),
                (
                    "accepted_scientific_name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="accepted scientific name",
                    ),
                ),
                (
                    "identified_by",
                    models.CharField(
                        blank=True,
                        default="Cortolima",
                        max_length=255,
                        verbose_name="identified by",
                    ),
                ),
                (
                    "identified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="identified date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="trees.genus",
                        verbose_name="genus",
                    ),
                ),
            ],
            options={
                "verbose_name": "species",
                "verbose_name_plural": "species",
                "ordering": ["accepted_scientific_name"],
            },
        ),
        migrations.AddField(
            model_name="biodiversityrecord",
            name="species",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="biodeversity_records",
                to="trees.species",
                verbose_name="species",
            ),
        ),
    ]
