# Generated by Django 5.1.7 on 2025-04-11 03:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Colombia", max_length=50, verbose_name="country"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        default="Tolima", max_length=50, verbose_name="department"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        default="Ibagué", max_length=50, verbose_name="municipality"
                    ),
                ),
                (
                    "site",
                    models.CharField(blank=True, max_length=50, verbose_name="site"),
                ),
                (
                    "populated_center",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="populated center"
                    ),
                ),
                (
                    "zone",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="zone"
                    ),
                ),
                (
                    "subzone",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="subzone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "ordering": ["country", "department", "municipality", "site"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "department", "municipality", "site"),
                        name="unique_place",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BiodiversityRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "common_names",
                    models.TextField(blank=True, verbose_name="common names"),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326, verbose_name="location"
                    ),
                ),
                (
                    "elevation_m",
                    models.FloatField(
                        blank=True, null=True, verbose_name="elevation (m)"
                    ),
                ),
                (
                    "recorded_by",
                    models.CharField(
                        blank=True,
                        default="Cortolima",
                        max_length=50,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="recorded date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "species",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biodiversity_records",
                        to="taxonomy.species",
                        verbose_name="species",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biodiversity_records",
                        to="biodiversity.place",
                        verbose_name="place",
                    ),
                ),
            ],
            options={
                "verbose_name": "biodiversity record",
                "verbose_name_plural": "biodiversity records",
                "ordering": ["species", "location"],
            },
        ),
    ]
