# Generated by Django 5.1.7 on 2025-04-18 20:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodiversityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('common_name', models.TextField(blank=True, verbose_name='common name')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='location')),
                ('elevation_m', models.FloatField(blank=True, null=True, verbose_name='elevation (m)')),
                ('recorded_by', models.CharField(blank=True, default='Cortolima', max_length=50, verbose_name='recorded by')),
                ('date', models.DateField(blank=True, null=True, verbose_name='recorded date')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biodiversity_records', to='places.site', verbose_name='site')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='biodiversity_records', to='taxonomy.species', verbose_name='species')),
            ],
            options={
                'verbose_name': 'biodiversity record',
                'verbose_name_plural': 'biodiversity records',
                'ordering': ['species', 'location'],
            },
        ),
    ]