# Generated by Django 5.1.7 on 2025-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversityrecord',
            name='common_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='common name'),
        ),
    ]
