# Generated by Django 5.1.7 on 2025-04-14 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodiversityrecord',
            name='common_names',
        ),
    ]
