# Generated by Django 5.1.7 on 2025-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0002_remove_biodiversityrecord_common_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversityrecord',
            name='original_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
