# Generated by Django 5.1.7 on 2025-04-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0002_alter_biodiversityrecord_common_name'),
        ('places', '0007_place_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversityrecord',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='biodiversity_records', to='places.neighborhood', verbose_name='neighborhood'),
            preserve_default=False,
        ),
    ]
