# Generated by Django 5.1.7 on 2025-05-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodiversity', '0004_alter_biodiversityrecord_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversityrecord',
            name='system_comment',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='system comment'),
        ),
    ]
