# Generated by Django 5.1.7 on 2025-04-18 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='department')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='places.country', verbose_name='country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='municipality')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='places.department', verbose_name='department')),
            ],
            options={
                'verbose_name_plural': 'municipalities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('site', models.CharField(max_length=50, verbose_name='site')),
                ('populated_center', models.CharField(max_length=50, verbose_name='populated center')),
                ('zone', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='zone')),
                ('subzone', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='subzone')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.municipality', verbose_name='municipality')),
            ],
            options={
                'ordering': ['municipality', 'site'],
                'constraints': [models.UniqueConstraint(fields=('municipality', 'site'), name='unique_place')],
            },
        ),
    ]
