# Generated by Django 5.1.7 on 2025-04-18 20:36

from django.db import migrations


def create_initial_places(apps, schema_editor):
    """Creates the initial country, department, and municipality records."""
    
    Country = apps.get_model('places', 'Country')
    Department = apps.get_model('places', 'Department')
    Municipality = apps.get_model('places', 'Municipality')
    
    # Create Colombia as the initial country
    colombia = Country.objects.create(name='Colombia')
    
    # Create Tolima as the initial department
    tolima = Department.objects.create(name='Tolima', country=colombia)
    
    # Create Ibagué as the initial municipality
    Municipality.objects.create(name='Ibagué', department=tolima)


def reverse_initial_places(apps, schema_editor):
    """Removes the initial country, department, and municipality records."""
    Country = apps.get_model('places', 'Country')
    Country.objects.filter(name='Colombia').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_places, reverse_initial_places),
    ]
