# Generated by Django 5.1.7 on 2025-04-26 22:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_create_initial_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='country boundary'),
        ),
        migrations.AddField(
            model_name='department',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='department boundary'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='municipality boundary'),
        ),
    ]
