# Generated by Django 5.1.7 on 2025-04-26 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_country_boundary_department_boundary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'ordering': ['name'], 'verbose_name': 'municipality', 'verbose_name_plural': 'municipalities'},
        ),
    ]
