# Generated by Django 5.1.7 on 2025-04-26 23:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_country_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='locality')),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='locality boundary')),
                ('calculated_area_m2', models.FloatField(blank=True, null=True, verbose_name='calculated area (m²)')),
                ('population_2019', models.PositiveIntegerField(blank=True, null=True, verbose_name='population 2019')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='places.municipality', verbose_name='municipality')),
            ],
            options={
                'verbose_name': 'locality',
                'verbose_name_plural': 'localities',
                'ordering': ['name'],
            },
        ),
    ]
