# Generated by Django 5.1.7 on 2025-04-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='locality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='places', to='places.locality', verbose_name='locality'),
            preserve_default=False,
        ),
    ]
