# Generated by Django 5.1.7 on 2025-04-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_locality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['site']},
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='municipality',
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('locality', 'site'), name='unique_place'),
        ),
    ]
