# Generated by Django 5.1.7 on 2025-04-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_place_locality'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_place',
        ),
        migrations.RemoveField(
            model_name='site',
            name='municipality',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50, verbose_name='site name'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('locality', 'name'), name='unique_place'),
        ),
    ]
