# Generated by Django 5.1.7 on 2025-04-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_options_remove_place_unique_place_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='place',
            name='unique_place',
        ),
        migrations.RemoveField(
            model_name='place',
            name='site',
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='nn', max_length=50, verbose_name='site name'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('locality', 'name'), name='unique_place'),
        ),
    ]
