# Generated by Django 5.1.7 on 2025-04-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_site_options_remove_site_unique_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='populated_center',
        ),
    ]
