# Generated by Django 5.1.7 on 2025-04-27 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_place_options_remove_place_unique_place_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Site',
        ),
    ]
