# Generated by Django 5.1.7 on 2025-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_department_name_alter_locality_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='calculated_area_m2',
            field=models.FloatField(blank=True, null=True, verbose_name='calculated area (m²)'),
        ),
    ]
