# Generated by Django 5.1.7 on 2025-04-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_neighborhood_calculated_area_m2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_place',
        ),
        migrations.RemoveField(
            model_name='site',
            name='locality',
        ),
    ]
