# Generated by Django 5.1.7 on 2025-04-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_site_options_remove_site_unique_place_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('name', 'zone', 'subzone'), name='unique_site_per_zone_subzone'),
        ),
    ]
