# Generated by Django 5.1.7 on 2025-03-23 17:40

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Reporter Name"
                    ),
                ),
                (
                    "reporter_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Reporter Email"
                    ),
                ),
                (
                    "reporter_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Reporter Phone"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="Location",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Address"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("hazard", "Hazardous Condition"),
                            ("damage", "Tree Damage"),
                            ("disease", "Disease or Pests"),
                            ("illegal_activity", "Illegal Activity"),
                            ("maintenance", "Needs Maintenance"),
                            ("request", "Planting Request"),
                            ("removal", "Removal Request"),
                            ("observation", "General Observation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Report Type",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="Priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("under_review", "Under Review"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reported At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Closed At"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="Admin Notes"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned To",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tree_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reporter",
                    ),
                ),
                (
                    "tree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="trees.tree",
                        verbose_name="Tree",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="UUID"
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("inspection", "Inspection"),
                            ("maintenance", "Maintenance"),
                            ("pruning", "Pruning"),
                            ("treatment", "Treatment"),
                            ("removal", "Removal"),
                            ("planting", "Planting"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Intervention Type",
                    ),
                ),
                ("date_performed", models.DateField(verbose_name="Date Performed")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("successful", "Successful"),
                            ("partial", "Partially Successful"),
                            ("unsuccessful", "Unsuccessful"),
                            ("needs_followup", "Needs Follow-up"),
                        ],
                        max_length=20,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "followup_notes",
                    models.TextField(blank=True, verbose_name="Follow-up Notes"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_interventions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="reports.report",
                        verbose_name="Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "ordering": ["-date_performed"],
            },
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="reports/%Y/%m/%d/", verbose_name="Image"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reports.report",
                        verbose_name="Report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Image",
                "verbose_name_plural": "Report Images",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
