# Generated by Django 5.1.7 on 2025-04-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='hfc',
            new_name='hcf',
        ),
    ]
