# Generated by Django 5.1.7 on 2025-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='attribute',
            field=models.CharField(choices=[('TH', 'trunk height'), ('HT', 'total height'), ('CD', 'crown diameter'), ('DBH', 'diameter at breast height'), ('VO', 'volume'), ('WD', 'wood density'), ('OT', 'other'), ('NO', 'not reported')], max_length=3, verbose_name='measured attribute'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='phytosanitary_status',
            field=models.CharField(choices=[('HE', 'healthy'), ('SI', 'sick'), ('CR', 'critically sick'), ('DE', 'dead'), ('NO', 'not reported')], default='NO', max_length=2, verbose_name='phytosanitary status'),
        ),
    ]
