# Generated by Django 5.1.7 on 2025-04-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_hfc_observation_hcf'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='photo_url',
            field=models.URLField(blank=True, help_text='URL of the photo associated with the observation', max_length=255, null=True, verbose_name='photo URL'),
        ),
    ]
