# Generated by Django 5.1.7 on 2025-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_measurement_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='original_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='original_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
