# Generated by Django 5.1.7 on 2025-04-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_observation_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('m', 'meters (m)'), ('m3', 'cubic meters (m3)'), ('cm', 'centimeters (cm)'), ('g/cm3', 'grams per cubic centimeter (g/cm3)'), ('NR', 'not reported')], default='NR', max_length=5, verbose_name='measurement unit'),
        ),
    ]
