# Generated by Django 5.1.7 on 2025-04-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='ab',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='ab'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='accompanying_collectors',
            field=models.CharField(blank=True, max_length=255, verbose_name='accompanying collectors'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bbs',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='bbs'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cap',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='cap'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ce',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='ce'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='civ',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='civ'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='coa',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='coa'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cra',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='cra'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='cre',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='cre'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='crg',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='crg'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='crh',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='crh'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='crt',
            field=models.CharField(choices=[('Y', 'yes'), ('N', 'no'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='crt'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='dm',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='dm'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ed',
            field=models.CharField(choices=[('GO', 'good'), ('FA', 'fair'), ('PO', 'poor'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='ed'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='hc',
            field=models.CharField(choices=[('NS', 'natural state'), ('ND', 'nutrient deficiency'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='hc'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='hcf',
            field=models.CharField(choices=[('NS', 'natural state'), ('ND', 'nutrient deficiency'), ('NR', 'not reported')], default='NR', max_length=2, verbose_name='hcf'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pa',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='pa'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pd',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='pd'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pe',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='pe'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ph',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='ph'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pi',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='pi'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='po',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='po'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='pp',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='pp'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='r_ce',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='r_ce'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='r_cr',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='r_cr'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='r_vol',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='r_vol'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='rd',
            field=models.CharField(choices=[('0', '0%'), ('20', '20%'), ('40', '40%'), ('60', '60%'), ('80', '80%'), ('100', '100%'), ('NR', 'not reported')], default='0', max_length=3, verbose_name='rd'),
        ),
    ]
