# Generated by Django 5.1.7 on 2025-04-11 03:41

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="family name"
                    ),
                ),
            ],
            options={
                "verbose_name": "family",
                "verbose_name_plural": "families",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="genus name"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genera",
                        to="taxonomy.family",
                        verbose_name="family",
                    ),
                ),
            ],
            options={
                "verbose_name": "genus",
                "verbose_name_plural": "genera",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Species",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="species name without the genus",
                        max_length=50,
                        verbose_name="species name",
                    ),
                ),
                (
                    "scientific_name",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.text.Concat(
                            "genus", models.Value(" "), "name"
                        ),
                        output_field=models.CharField(max_length=101),
                        verbose_name="scientific genus and species name",
                    ),
                ),
                (
                    "accepted_scientific_name",
                    models.CharField(
                        help_text="scientific genus and species name with optional reference to whom named it",
                        max_length=50,
                        unique=True,
                        verbose_name="accepted scientific name",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("EX", "exotic"), ("NA", "native"), ("UN", "unknown")],
                        default="UN",
                        max_length=2,
                        verbose_name="origin",
                    ),
                ),
                (
                    "iucn_status",
                    models.CharField(
                        choices=[
                            ("DD", "data deficient"),
                            ("LC", "least concern"),
                            ("NT", "near threatened"),
                            ("VU", "vulnerable"),
                            ("EN", "endangered"),
                            ("CR", "critically endangered"),
                            ("EW", "extinct in the wild"),
                            ("EX", "extinct"),
                            ("NE", "not evaluated"),
                        ],
                        default="NE",
                        max_length=2,
                        verbose_name="IUCN status",
                    ),
                ),
                (
                    "growth_habit",
                    models.CharField(
                        choices=[
                            ("TR", "tree"),
                            ("PT", "palm tree"),
                            ("SH", "shrub"),
                            ("UN", "unknown"),
                        ],
                        default="UN",
                        max_length=2,
                        verbose_name="growth habit",
                    ),
                ),
                (
                    "identified_by",
                    models.CharField(
                        blank=True,
                        default="Cortolima",
                        max_length=255,
                        verbose_name="identified by",
                    ),
                ),
                (
                    "identified_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="identified date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "genus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="species",
                        to="taxonomy.genus",
                        verbose_name="genus",
                    ),
                ),
            ],
            options={
                "verbose_name": "species",
                "verbose_name_plural": "species",
                "ordering": ["scientific_name"],
            },
        ),
    ]
