# Generated by Django 5.1.7 on 2025-04-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='traitvalue',
            name='min_value_less_than_max_value',
        ),
    ]
