# Generated by Django 5.1.7 on 2025-04-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='common_name',
            field=models.TextField(blank=True, verbose_name='common names'),
        ),
        migrations.AddField(
            model_name='species',
            name='gbif_id',
            field=models.CharField(blank=True, help_text='GBIF species identifier', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='accepted_scientific_name',
            field=models.CharField(help_text='scientific genus and species name with optional reference to whom named it', max_length=150, unique=True, verbose_name='accepted scientific name'),
        ),
    ]
