# Generated by Django 5.1.7 on 2025-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_remove_traitvalue_min_value_less_than_max_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='origin',
            field=models.CharField(choices=[('NT', 'native'), ('CU', 'cultivated'), ('NC', 'native | cultivated'), ('NU', 'naturalized'), ('NL', 'naturalized | cultivated'), ('EN', 'endemic'), ('NI', 'not identified')], default='NI', max_length=2, verbose_name='origin'),
        ),
    ]
