# Generated by Django 5.1.7 on 2025-04-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_alter_species_origin'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='traitvalue',
            constraint=models.UniqueConstraint(fields=('trait', 'functional_group'), name='unique_trait_per_functional_group'),
        ),
    ]
