# Generated by Django 5.1.7 on 2025-04-09 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("trees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, verbose_name="uuid"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, default="No reportado", verbose_name="comments"
                    ),
                ),
                (
                    "reproductive_condition",
                    models.CharField(
                        choices=[
                            ("FL", "flowering"),
                            ("FR", "fruiting"),
                            ("SE", "seedling"),
                            ("VE", "vegetative"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="reproductive condition",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, default="No reportado", verbose_name="observations"
                    ),
                ),
                (
                    "phytosanitary_status",
                    models.CharField(
                        choices=[
                            ("HE", "healthy"),
                            ("IN", "infected"),
                            ("IF", "infested"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="phytosanitary status",
                    ),
                ),
                (
                    "accompanying_collectors",
                    models.TextField(
                        blank=True,
                        default="No reportado",
                        verbose_name="accompanying collectors",
                    ),
                ),
                ("use", models.URLField(blank=True, null=True, verbose_name="use")),
                (
                    "physical_condition",
                    models.CharField(
                        choices=[
                            ("GO", "good"),
                            ("BA", "bad"),
                            ("RE", "regular"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="physical condition",
                    ),
                ),
                (
                    "foliage_density",
                    models.CharField(
                        choices=[
                            ("DE", "dense"),
                            ("MO", "moderate"),
                            ("SP", "sparse"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="foliage density",
                    ),
                ),
                (
                    "aesthetic_value",
                    models.CharField(
                        choices=[
                            ("DE", "desirable"),
                            ("EM", "emblematic"),
                            ("ES", "essential"),
                            ("UN", "unacceptable"),
                            ("IN", "indifferent"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="aesthetic value",
                    ),
                ),
                (
                    "growth_phase",
                    models.CharField(
                        choices=[
                            ("F1", "F1"),
                            ("F2", "F2"),
                            ("F3", "F3"),
                            ("UN", "unknown"),
                        ],
                        default="UN",
                        max_length=12,
                        verbose_name="growth phase",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[("EX", "exotic"), ("NA", "native"), ("UN", "unknown")],
                        default="UN",
                        max_length=12,
                        verbose_name="origin",
                    ),
                ),
                (
                    "iucn_status",
                    models.CharField(
                        choices=[
                            ("DD", "data deficient"),
                            ("LC", "least concern"),
                            ("NT", "near threatened"),
                            ("VU", "vulnerable"),
                            ("EN", "endangered"),
                            ("CR", "critically endangered"),
                            ("EW", "extinct in the wild"),
                            ("EX", "extinct"),
                            ("NE", "not evaluated"),
                        ],
                        default="NE",
                        max_length=24,
                        verbose_name="IUCN status",
                    ),
                ),
                (
                    "growth_habit",
                    models.CharField(
                        choices=[
                            ("TR", "tree"),
                            ("SH", "shrub"),
                            ("HE", "herb"),
                            ("CL", "climber"),
                            ("NO", "none"),
                        ],
                        default="NO",
                        max_length=12,
                        verbose_name="growth habit",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="observation date"
                    ),
                ),
                (
                    "recorded_by",
                    models.CharField(
                        blank=True,
                        default="Cortolima",
                        max_length=255,
                        verbose_name="recorded by",
                    ),
                ),
                (
                    "biodiversity_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="trees.biodiversityrecord",
                        verbose_name="biodiversity record",
                    ),
                ),
            ],
            options={
                "verbose_name": "observation",
                "verbose_name_plural": "observations",
                "ordering": ["date"],
            },
        ),
    ]
